import type { DirectorioItem } from "./types";

export const HOTELES: DirectorioItem[] = [
  { id: "sheraton", name: "Sheraton Asunción", zone: "carmelitas", desc: "Hotel 5 estrellas, desayuno buffet, piscina y spa.", image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=533&fit=crop", url: "https://www.booking.com/search.html?ss=Sheraton+Asuncion", stars: 5, badge: "Recomendado" },
  { id: "esplendor", name: "Esplendor by Wyndham", zone: "villa-morra", desc: "Hotel 4 estrellas boutique, excelente ubicación.", image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400&h=533&fit=crop", url: "https://www.booking.com/search.html?ss=Esplendor+Asuncion", stars: 4 },
  { id: "dazzler", name: "Dazzler Asunción", zone: "villa-morra", desc: "Hotel 4 estrellas moderno con piscina.", image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=400&h=533&fit=crop", url: "https://www.booking.com/search.html?ss=Dazzler+Asuncion", stars: 4 },
  { id: "nh", name: "NH Asunción", zone: "centro", desc: "Hotel 4 estrellas en pleno centro.", image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=400&h=533&fit=crop", url: "https://www.booking.com/search.html?ss=NH+Asuncion", stars: 4 },
  { id: "lamision", name: "La Misión Hotel Boutique", zone: "centro", desc: "Hotel boutique de lujo en el centro histórico.", image: "https://images.unsplash.com/photo-1549638441-b787d2e11f14?w=400&h=533&fit=crop", url: "https://www.booking.com/search.html?ss=La+Mision+Hotel+Boutique+Asuncion", stars: 5 },
  { id: "granados", name: "Granados Park Hotel", zone: "centro", desc: "Hotel clásico, excelente servicio.", image: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=400&h=533&fit=crop", url: "https://www.booking.com/search.html?ss=Granados+Park+Asuncion", stars: 4 },
  { id: "holiday", name: "Holiday Inn Express", zone: "carmelitas", desc: "Hotel moderno cerca del shopping.", image: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=400&h=533&fit=crop", url: "https://www.booking.com/search.html?ss=Holiday+Inn+Express+Asuncion", stars: 4 },
  { id: "terranova", name: "Hotel Terranova", zone: "carmelitas", desc: "Hotel ejecutivo en Carmelitas.", image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=400&h=533&fit=crop", url: "https://www.booking.com/search.html?ss=Hotel+Terranova+Asuncion", stars: 3 },
  { id: "croquignole", name: "Hotel Croquignole", zone: "centro", desc: "Hotel clásico con encanto en el centro.", image: "https://images.unsplash.com/photo-1590490359683-658d3d23f972?w=400&h=533&fit=crop", url: "https://www.booking.com/search.html?ss=Hotel+Croquignole+Asuncion", stars: 3 },
  { id: "aristón", name: "Hotel Aristón", zone: "centro", desc: "Hotel cómodo en pleno microcentro.", image: "https://images.unsplash.com/photo-1583071299210-c6c8b6e7c84f?w=400&h=533&fit=crop", url: "https://www.booking.com/search.html?ss=Hotel+Ariston+Asuncion", stars: 3 },
  { id: "ceaser", name: "Hotel Ceasar Palace", zone: "villa-morra", desc: "Hotel ejecutivo con piscina.", image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=400&h=533&fit=crop", url: "https://www.booking.com/search.html?ss=Ceasar+Palace+Asuncion", stars: 3 },
];
