import type { DirectorioItem } from "./types";

export const SHOPPING: DirectorioItem[] = [
  { id: "shopping-del-sol", name: "Shopping del Sol", zone: "villa-morra", desc: "El shopping más grande de Asunción. Cines, patio de comidas, tiendas.", image: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=400&h=533&fit=crop", url: "https://maps.google.com/?q=Shopping+del+Sol+Asuncion", tipo: "Shopping", horario: "10:00 - 22:00" },
  { id: "mcal-lopez", name: "Mariscal López Shopping", zone: "carmelitas", desc: "Shopping moderno con cines, patio de comidas, marcas internacionales.", image: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=400&h=533&fit=crop", url: "https://maps.google.com/?q=Mariscal+Lopez+Shopping+Asuncion", tipo: "Shopping", horario: "10:00 - 22:00" },
  { id: "paseo-la-galeria", name: "Paseo La Galería", zone: "villa-morra", desc: "Centro comercial con cine, restaurants y tiendas.", image: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=400&h=533&fit=crop", url: "https://maps.google.com/?q=Paseo+La+Galeria+Asuncion", tipo: "Shopping", horario: "10:00 - 21:00" },
  { id: "pinedo", name: "Pinedo Shopping", zone: "luque", desc: "Shopping en Luque, cerca del aeropuerto.", image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=533&fit=crop", url: "https://maps.google.com/?q=Pinedo+Shopping+Luque", tipo: "Shopping", horario: "10:00 - 21:00" },
  { id: "catedral", name: "Catedral Shopping", zone: "centro", desc: "Shopping en pleno centro sobre la peatonal.", image: "https://images.unsplash.com/photo-1481437156560-3205f6a55735?w=400&h=533&fit=crop", url: "https://maps.google.com/?q=Catedral+Shopping+Asuncion", tipo: "Shopping", horario: "09:00 - 20:00" },
  { id: "san-lorenzo", name: "San Lorenzo Shopping", zone: "san-lorenzo", desc: "Centro comercial en San Lorenzo.", image: "https://images.unsplash.com/photo-1534297614086-4c0d15cdb75e?w=400&h=533&fit=crop", url: "https://maps.google.com/?q=San+Lorenzo+Shopping", tipo: "Shopping", horario: "10:00 - 21:00" },
  { id: "mall-excelsior", name: "Mall Excelsior", zone: "centro", desc: "Centro comercial boutique en el centro.", image: "https://images.unsplash.com/photo-1555529771-2784f6e18ee9?w=400&h=533&fit=crop", url: "https://maps.google.com/?q=Mall+Excelsior+Asuncion", tipo: "Shopping", horario: "10:00 - 20:00" },
];
