import type { DirectorioItem } from "./types";

export const SHOPPING: DirectorioItem[] = [
  { id: "catedral", name: "Catedral Shopping", zone: "centro", desc: "Shopping en pleno centro sobre la peatonal.", image: "https://images.unsplash.com/photo-1481437156560-3205f6a55735?w=400&h=533&fit=crop", url: "https://www.google.com/maps?q=Catedral%20Shopping", tipo: "Shopping", horario: "09:00 - 20:00" },
  { id: "mall-excelsior", name: "MALL EXCELSIOR", zone: "centro", desc: "Shopping Mall Excelsior es un moderno centro comercial que combina compras, gastronomía y entretenimiento en un solo...", image: "https://visitparaguay.travel/storage/places/68a33bdb4c82a.webp", url: "https://www.google.com/maps?q=MALL%20EXCELSIOR", tipo: "Shopping", horario: "10:00 - 22:00" },
  { id: "mariscal-lopez-shopping", name: "MARISCAL LÓPEZ SHOPPING", zone: "carmelitas", desc: "Ubicado en el corazón de Asunción, el Shopping Mariscal López es uno de los centros comerciales más tradicionales y r...", image: "https://visitparaguay.travel/storage/places/aMvHqfm7HXa2Wynt0BXjBoi9nXp01B43LxFVxFhy.jpg", url: "https://www.google.com/maps?q=MARISCAL%20L%C3%93PEZ%20SHOPPING", tipo: "Shopping", horario: "10:00 - 22:00" },
  { id: "paseo-la-galeria", name: "PASEO LA GALERÍA", zone: "villa-morra", desc: "Paseo La Galería es uno de los centros comerciales y empresariales más destacados del Paraguay", image: "https://visitparaguay.travel/storage/places/oZ78EzSOklYrWRTjLw54gW9kNRAKUFH6AoefZZFS.jpg", url: "https://www.google.com/maps?q=PASEO%20LA%20GALER%C3%8DA", tipo: "Shopping", horario: "10:00 - 22:00" },
  { id: "pinedo-shopping", name: "PINEDO SHOPPING", zone: "luque", desc: "Shopping Pinedo es un moderno centro comercial que ofrece una experiencia completa de compras, gastronomía y entreten...", image: "https://visitparaguay.travel/storage/places/68a3434765cd5.webp", url: "https://www.google.com/maps?q=PINEDO%20SHOPPING", tipo: "Shopping", horario: "10:00 - 22:00" },
  { id: "shopping-china", name: "SHOPPING CHINA", zone: "ciudad-del-este", desc: "Shopping China, es el mayor y más tradicional comercio de importados del Paraguay, es una empresa familiar, fundada e...", image: "https://visitparaguay.travel/storage/places/pAa3yqr5qD6cw9GVbPoaSWOFjKiXaK1cQTBgVq7p.jpg", url: "https://www.google.com/maps?q=SHOPPING%20CHINA", tipo: "Shopping", horario: "10:00 - 22:00" },
  { id: "shopping-costanera", name: "SHOPPING COSTANERA", zone: "encarnacion", desc: "El Shopping Costanera se posiciona como el primer centro comercial integral de la ciudad de Encarnación, ofreciendo u...", image: "https://visitparaguay.travel/storage/places/689b4cdeb4189.webp", url: "https://www.google.com/maps?q=SHOPPING%20COSTANERA", tipo: "Shopping", horario: "10:00 - 22:00" },
  { id: "shopping-del-este", name: "SHOPPING DEL ESTE", zone: "ciudad-del-este", desc: "Ubicado en la entrada principal de Ciudad del Este, Shopping Del Este es uno de los centros comerciales más tradicion...", image: "https://visitparaguay.travel/storage/places/689f99171d4ae.webp", url: "https://www.google.com/maps?q=SHOPPING%20DEL%20ESTE", tipo: "Shopping", horario: "10:00 - 22:00" },
  { id: "shopping-del-sol", name: "Shopping del Sol", zone: "villa-morra", desc: "El shopping más grande de Asunción. Cines, patio de comidas, tiendas.", image: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=400&h=533&fit=crop", url: "https://www.google.com/maps?q=Shopping%20del%20Sol", tipo: "Shopping", horario: "10:00 - 22:00" },
  { id: "shopping-multiplaza", name: "SHOPPING MULTIPLAZA", zone: "villa-morra", desc: "Ubicado en una zona estratégica de Asunción, el Shopping Multiplaza es un centro comercial que ofrece una amplia vari...", image: "https://visitparaguay.travel/storage/places/a9K7D36SxCNK6oSG30O7b5rX9jnSY5WdhUxgWB7A.jpg", url: "https://www.google.com/maps?q=SHOPPING%20MULTIPLAZA", tipo: "Shopping", horario: "10:00 - 22:00" },
  { id: "shopping-paris", name: "SHOPPING PARIS", zone: "ciudad-del-este", desc: "Ubicado a solo unos pasos del Puente de la Amistad, Shopping Paris es el centro comercial más moderno y completo de l...", image: "https://visitparaguay.travel/storage/places/68a3637bd0f21.webp", url: "https://www.google.com/maps?q=SHOPPING%20PARIS", tipo: "Shopping", horario: "10:00 - 22:00" },
  { id: "shopping-san-lorenzo", name: "SHOPPING SAN LORENZO", zone: "san-lorenzo", desc: "Shopping San Lorenzo es un centro comercial moderno que ofrece una experiencia completa de compras, entretenimiento y...", image: "https://visitparaguay.travel/storage/places/68a33d8b74739.webp", url: "https://www.google.com/maps?q=SHOPPING%20SAN%20LORENZO", tipo: "Shopping", horario: "10:00 - 22:00" },
];
