import type { DirectorioItem } from "./types";

export const TEATROS: DirectorioItem[] = [
  {
    id: "teatro-municipal",
    name: "Teatro Municipal Ignacio A. Pane",
    zone: "centro",
    desc: "El teatro más antiguo de Asunción, ícono cultural de la ciudad.",
    image: "https://visitparaguay.travel/storage/places/2283-1.webp",
    url: "https://visitparaguay.travel/places/teatro-municipal-ignacio-a-pane",
    badge: "Histórico",
  },
  {
    id: "teatro-guarani",
    name: "Teatro Guaraní",
    zone: "centro",
    desc: "Sala principal del Centro Cultural de la República, 791 espectadores.",
    image: "https://visitparaguay.travel/storage/places/FfqiAbAFnWcT3V38XJaH835vDBhPiu38opiXXANr.jpg",
    url: "https://visitparaguay.travel/places/teatro-guarani",
  },
  {
    id: "teatro-latino",
    name: "Teatro Latino",
    zone: "centro",
    desc: "Uno de los espacios culturales más emblemáticos de Asunción.",
    image: "https://visitparaguay.travel/storage/places/UHx1jqWIPPn0kwBxPvMGman7Gh10ZWW9CNfiIG9F.jpg",
    url: "https://visitparaguay.travel/places/teatro-latino",
  },
  {
    id: "arlequin-teatro",
    name: "Arlequín Teatro",
    zone: "centro",
    desc: "Fundado en 1982, espacio emblemático de teatro independiente.",
    image: "https://visitparaguay.travel/storage/places/fsS9cCzlf1CBu7lndOj3vDECw2RY9gHW3EYBZH9W.jpg",
    url: "https://visitparaguay.travel/places/arlequin-teatro",
  },
  {
    id: "teatro-americas",
    name: "Teatro de las Américas",
    zone: "centro",
    desc: "Del Centro Cultural Paraguayo Americano, en pleno microcentro.",
    image: "https://visitparaguay.travel/storage/places/68514deaabae4.webp",
    url: "https://visitparaguay.travel/places/teatro-de-las-americas-del-centro-cultural-paraguayo-americano",
  },
  {
    id: "cema",
    name: "Centro Municipal de Arte CEMA",
    zone: "centro",
    desc: "Edificio histórico que alberga exposiciones y espectáculos culturales.",
    image: "https://visitparaguay.travel/storage/places/689b5773ef78f.webp",
    url: "https://visitparaguay.travel/places/centro-municipal-de-arte-cema-prof-julian-rojas-chilavert",
  },
  {
    id: "centro-paraguayo-japones",
    name: "Centro Paraguayo Japonés",
    zone: "centro",
    desc: "Institución cultural y educativa de referencia en Asunción.",
    image: "https://visitparaguay.travel/storage/places/6877e0c523ee4.webp",
    url: "https://visitparaguay.travel/places/centro-paraguayo-japones",
  },
  {
    id: "jockey-club",
    name: "Jockey Club del Paraguay",
    zone: "villa-morra",
    desc: "Espacio multifuncional para eventos culturales y sociales.",
    image: "https://visitparaguay.travel/storage/places/680bf456d2436.webp",
    url: "https://visitparaguay.travel/places/jockey-club-del-paraguay",
  },
  {
    id: "anfiteatro-flores",
    name: "Anfiteatro José Asunción Flores",
    zone: "san-bernardino",
    desc: "Espacio cultural y artístico emblemático a orillas del lago.",
    image: "https://visitparaguay.travel/storage/places/6979fa6403310.webp",
    url: "https://visitparaguay.travel/places/anfiteatro-jose-asuncion-flores",
  },
];
